-- beta.26 download safety: progress domains stay separate and low-memory work hibernates.
local downloader=assert(io.open('miuread.koplugin/miuread/downloader.lua','rb')):read('*a')
local task=assert(io.open('miuread.koplugin/miuread/download_task.lua','rb')):read('*a')
local cfg=assert(io.open('miuread.koplugin/miuread/config.lua','rb')):read('*a')
assert(not downloader:find('submit_progress',1,true),'Downloader must not submit reading progress')
assert(not downloader:find('upload_local_progress',1,true),'Downloader must not invoke UI progress upload')
assert(task:find('request_hibernate("memory_pressure")',1,true),'running low-memory guard hibernates')
assert(task:find('running_low_memory_samples',1,true),'low-memory guard requires consecutive samples')
assert(cfg:find('HEAVY_DOWNLOAD_RUNNING_LOW_SAMPLES = 2',1,true),'two samples required')
print('download safety: PASS')
