-- 5.9 long-book contract: raw percent never verifies a cloud position; chapter+co
-- remains authoritative. beta.13 resolves/verifies a candidate before visible jump.
local mainf=assert(io.open('miuread.koplugin/main.lua','rb')); local main=mainf:read('*a'); mainf:close()
local syncf=assert(io.open('miuread.koplugin/miuread/sync.lua','rb')); local sync=syncf:read('*a'); syncf:close()
assert(main:find('mapped_percent_equivalent',1,true)==nil,'percent equivalence cannot verify exact mismatch')
assert(main:find('chapter_offset_mismatch',1,true) and main:find('co_tolerance',1,true),'chapter+co exact verification retained')
assert(sync:find('resolve_chapter_anchor_target',1,true),'chapter candidate resolver retained')
assert(sync:find('resolve_remote_candidate_xpointer',1,true),'remote candidate preflight retained')
assert(main:find('_G.__MIUREAD_POSITION_RESOLUTION.decide',1,true),'long-book conflict goes through automatic resolver')
assert(main:find('text="使用云端位置"',1,true)==nil and main:find('text="使用本机位置并上传"',1,true)==nil,'old chapter conflict chooser removed')
assert(main:find('callback=function(ok,actual_position)',1,true),'verified remote jump persists actual exact position')
assert(main:find('remote_exact_coordinate_missing',1,true) and main:find('_set_progress_write_fence',1,true),'remote percent without exact coordinate cannot authorize local overwrite')
local a=assert(main:find('function Plugin:_use_remote_position',1,true))
local b=assert(main:find('function Plugin:on_remote_source_conflict',a+1,true))
local use=main:sub(a,b-1)
local verify=assert(use:find('resolve_xpointer_progress',1,true),'candidate preflight missing')
local jump=assert(use:find('jump_xpointer(candidate_xp)',verify,true),'verified jump missing')
assert(verify<jump,'visible jump must follow exact candidate verification')
assert(not use:find('remote_verification_failed_rollback',1,true),'beta.13 must not use visible rollback for failed verification')
print('long book anchor: PASS')
