local f=assert(io.open("miuread.koplugin/main.lua","rb")); local main=f:read("*a"); f:close()
assert(main:find("local_updated_at=tonumber(prior.updated_at or 0)",1,true),"opening resolver must use only durable reading-event freshness")
assert(not main:find("prior.updated_at or prior.captured_at",1,true),"captured_at freshness fallback removed")
assert(not main:find("prior.updated_at or session.progress_upload_verified_at",1,true),"upload/decision timestamps cannot make local newer")
assert(main:find("stale cloud observation ignored",1,true),"stale remote diagnostic exists")
assert(main:find("prefer_nonstale_remote",1,true),"remote stale guard wired")
assert(main:find("local_pos and local_pos.updated_at or 0",1,true),"shelf resolver uses event freshness only")
print("cloud freshness contract: PASS")
