-- 5.9 beta.5 long-book contract: percent only navigates; chapter+co verifies; ambiguous freshness is fenced.
local main=assert(io.open('miuread.koplugin/main.lua','rb')):read('*a')
assert(main:find('mapped_percent_equivalent',1,true)==nil,'percent equivalence cannot verify exact mismatch')
assert(main:find('chapter_offset_mismatch',1,true) and main:find('co_tolerance',1,true),'chapter+co exact verification retained')
assert(main:find('chapter_anchor_rescue',1,true) or main:find('chapter anchor',1,true),'chapter rescue retained')
assert(main:find('_G.__MIUREAD_POSITION_RESOLUTION.decide',1,true),'long-book conflict goes through automatic resolver')
assert(main:find('text="使用云端位置"',1,true)==nil and main:find('text="使用本机位置并上传"',1,true)==nil,'old chapter conflict chooser removed')
assert(main:find('callback=function(ok,actual_position',1,true),'verified remote jump persists actual exact position')
assert(main:find('remote_exact_coordinate_missing',1,true) and main:find('_set_progress_write_fence',1,true),'remote percent without exact coordinate cannot authorize local overwrite')
assert(main:find('remote_verification_failed_rollback',1,true),'failed exact verification rolls back to pre-jump local position')
print('long book anchor: PASS')
