local main=assert(io.open('miuread.koplugin/main.lua','rb')):read('*a')
local lib=assert(io.open('miuread.koplugin/miuread/library.lua','rb')):read('*a')
local dl=assert(io.open('miuread.koplugin/miuread/downloader.lua','rb')):read('*a')
assert(main:find('_sync_home_pending({silent=true,source="auth_success"})',1,true),'auth success retries safe sync')
assert(main:find('_home_refresh_remote(true,false)',1,true),'auth success refreshes cloud shelf')
assert(main:find('_network_recovery_generation',1,true),'network recovery is debounced')
assert(main:find('_auto_position_check_user_interacted',1,true),'all automatic checks guard late jumps')
assert(main:find('automatic_check_after_user_interaction',1,true),'interaction keeps current local position')
assert(lib:find('function Library:account_rows',1,true) and lib:find('for _,remote in ipairs(remote_rows or {}) do',1,true),'account shelf membership is cloud-authoritative')
assert(lib:find('function Library:generated_rows',1,true) and lib:find('append(local_books)',1,true),'downloaded EPUB remains in generated shelf independent of cloud membership')
assert(not dl:find('progress_submit',1,true),'downloader has no reading progress submit path')
print('cloud mirror contract: PASS')
