local store=assert(io.open('miuread.koplugin/miuread/store.lua','rb')):read('*a')
local a=assert(store:find('if schema<136 then',1,true),'schema136 block')
local b=store:find('logger.info("[MiuRead][Migration] schema 135 -> 136 done"',a,true)
assert(b,'schema136 end')
local block=store:sub(a,b)
assert(block:find('position_state',1,true),'position state seeded')
assert(block:find('fetched_at',1,true),'fetch time separated from update time')
assert(not block:find('api:',1,true) and not block:find('sync:',1,true),'migration does not access network or upload')
assert(not block:find('jump',1,true),'migration never moves current reading position')
print('schema136 contract: PASS')
