from pathlib import Path
import sys
root=Path(__file__).resolve().parents[1]
main=(root/'miuread.koplugin/main.lua').read_text(encoding='utf-8')
sync=(root/'miuread.koplugin/miuread/sync.lua').read_text(encoding='utf-8')
store=(root/'miuread.koplugin/miuread/store.lua').read_text(encoding='utf-8')
worker=(root/'miuread.koplugin/miuread/legacy/read_report_worker.lua').read_text(encoding='utf-8')
precise=(root/'miuread.koplugin/miuread/precise_position.lua').read_text(encoding='utf-8')
source=(root/'miuread.koplugin/miuread/source_position.lua').read_text(encoding='utf-8')
posmap=(root/'miuread.koplugin/miuread/annotations/posmap.lua').read_text(encoding='utf-8')
config=(root/'miuread.koplugin/miuread/config.lua').read_text(encoding='utf-8')
meta=(root/'miuread.koplugin/_meta.lua').read_text(encoding='utf-8')
ch=(root/'CHANGELOG.md').read_text(encoding='utf-8')
workflow=(root/'.github/workflows/release-beta.yml').read_text(encoding='utf-8')
checks=[]
def ok(cond,msg): checks.append((bool(cond),msg))
ok('VERSION = "5.9.1-beta.1"' in config,'config version 5.9.1-beta.1')
ok('version = "5.9.1-beta.1"' in meta,'metadata version 5.9.1-beta.1')
ok(ch.startswith('## 5.9.1-beta.1'),'5.9.1-beta.1 changelog first')
ok('SCHEMA = 136' in config,'schema remains 136')
ok('SOURCE_ANCHOR_WORDS = {24, 16, 12}' in precise,'beta19 multi-anchor sizes retained')
ok('anchor_candidates = anchor_candidates' in precise,'beta19 captured anchor set retained')
ok('local function anchor_variants(anchor)' in source,'beta19 source anchor variants retained')
ok('anchor_coordinate_conflict' in source,'beta19 coordinate-conflict fail closed retained')
ok('{images=false, fresh_context=true}' in source,'beta18 fresh source context retained')
ok('function PosMap.locateSource' in posmap,'beta19 source-only normalization retained')
ok('reliable_text_anchor_landing' in main,'beta19 reliable cloud text landing retained')
ok('function Plugin:_normalize_exact_progress_snapshot' in main,'exact snapshot normalizer')
ok('safe=true,coordinate_safe=true,precise=true' in main,'passive exact safety flags')
ok('progress_exact_snapshot_repair_591b1' in store,'beta19 exact snapshot migration repair')
ok('progress_upload_state="pending_send"' in store,'repair restores unsent exact pending_send')
ok('anchor=U.copy(anchor)' in sync,'ReadingEnd source failure returns immutable anchor')
ok('pending_unresolved_position=row' in main and 'source_anchor=type(source_anchor)=="table"' in main,'durable recovery capsule')
ok('function Sync:resolve_saved_progress_anchor' in sync,'Home saved-anchor resolver')
ok('function Plugin:_recover_pending_progress_anchor' in main,'Home saved-anchor recovery pipeline')
ok('can_recover_anchor=anchor_only and saved_anchor~=nil' in main,'anchor recovery classified as executable action')
ok('local_coordinate_unresolved=true' in main,'unresolved state included in failure FSM')
ok('can_clear_stale=replayable~=true and not (anchor_only and saved_anchor~=nil)' in main,'recoverable anchors not stale')
ok('text="恢复精确位置"' in main,'manual anchor recovery action')
ok('lightweight service exited after requested stop' in sync,'ReadReport requested stop is informational')
ok('local refreshed=refresh_remote_anchor(client, book_id, book)' in worker,'ReadReport fresh GET cloud guard retained')
ok('remote_wire_anchor' in sync,'remote wire anchor retained')
ok('POSITION_CLOCK_SKEW_GRACE_SECONDS = 30' in config,'30s clock skew guard retained')
ok('lua5.1 tools/test_591_beta1_progress_recovery.lua' in workflow,'new recovery contract in release workflow')
ok('python3 tools/verify_591_beta1.py' in workflow,'new verifier in release workflow')
ok('python3 tools/verify_590_beta19.py' not in workflow,'release workflow no longer runs version-pinned beta19 verifier')
failed=[m for c,m in checks if not c]
for c,m in checks: print(('PASS' if c else 'FAIL')+': '+m)
print(f'checks={len(checks)} failures={len(failed)}')
if failed: sys.exit(1)
